# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: g_grpc-fix.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'g_grpc-fix.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10g_grpc-fix.proto\x12\x08ggrpcfix\"\x1e\n\x0cPriceRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"J\n\x0bPriceUpdate\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0b\n\x03\x62id\x18\x02 \x01(\x01\x12\x0b\n\x03\x61sk\x18\x03 \x01(\x01\x12\x11\n\tts_micros\x18\x04 \x01(\x03\x32O\n\x0cPriceService\x12?\n\x0cStreamPrices\x12\x16.ggrpcfix.PriceRequest\x1a\x15.ggrpcfix.PriceUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'g_grpc_fix_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICEREQUEST']._serialized_start=30
  _globals['_PRICEREQUEST']._serialized_end=60
  _globals['_PRICEUPDATE']._serialized_start=62
  _globals['_PRICEUPDATE']._serialized_end=136
  _globals['_PRICESERVICE']._serialized_start=138
  _globals['_PRICESERVICE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
