# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import g_grpc_fix_pb2 as g__grpc__fix__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in g_grpc_fix_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PriceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPrices = channel.unary_stream(
                '/ggrpcfix.PriceService/StreamPrices',
                request_serializer=g__grpc__fix__pb2.PriceRequest.SerializeToString,
                response_deserializer=g__grpc__fix__pb2.PriceUpdate.FromString,
                _registered_method=True)


class PriceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamPrices(self, request, context):
        """Server-streaming RPC: client sends one PriceRequest, then receives a
        continuous stream of PriceUpdate messages until the server or client
        closes the stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PriceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPrices': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPrices,
                    request_deserializer=g__grpc__fix__pb2.PriceRequest.FromString,
                    response_serializer=g__grpc__fix__pb2.PriceUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ggrpcfix.PriceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ggrpcfix.PriceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PriceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ggrpcfix.PriceService/StreamPrices',
            g__grpc__fix__pb2.PriceRequest.SerializeToString,
            g__grpc__fix__pb2.PriceUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
